services:
  pipeline-gpu:
    build:
      context: ..
      dockerfile: docker/Dockerfile.gpu
    image: edge-roi-gpu
    working_dir: /app
    gpus: all
    volumes:
      - ../data:/app/data
      - ../models:/app/models
      - ../outputs:/app/outputs
    command: [ "bash", "docker/run_pipeline.sh" ]

  compression-gpu:
    profiles: [ "stage-tools" ]
    build:
      context: ..
      dockerfile: docker/Dockerfile.gpu
    image: edge-roi-gpu
    working_dir: /app
    gpus: all
    volumes:
      - ../data:/app/data
      - ../models:/app/models
      - ../outputs:/app/outputs
    command: [ "bash", "docker/run_compression.sh" ]

  decompression-gpu:
    profiles: [ "stage-tools" ]
    build:
      context: ..
      dockerfile: docker/Dockerfile.gpu
    image: edge-roi-gpu
    working_dir: /app
    gpus: all
    volumes:
      - ../data:/app/data
      - ../models:/app/models
      - ../outputs:/app/outputs
    command: [ "bash", "docker/run_decompression.sh" ]
